sudo: required
dist: trusty
language: go
## home folder is /home/travis/gopath/src/github.com/radanalyticsio/radanalyticsio.github.io
services:
- docker
matrix:
  include:
    - env: TO_TEST=pyspark-templates
    - env: TO_TEST=java-templates
    - env: TO_TEST=scala-templates
  fast_finish: true

before_install:
## add insecure-registry and restart docker
- export TEST_DIR=`pwd`
- export ORIGIN_DIR=$TEST_DIR/../origin
- ./travis-helpers/prepare.sh

install:
- git clone https://github.com/radanalyticsio/oshinko-s2i
- sudo chmod -R a+rwX $TEST_DIR/oshinko-s2i
- cp resources.yaml $TEST_DIR/oshinko-s2i/test/e2e/resources

before_script:
script:
- if [ "$TO_TEST" = "pyspark-templates" ]; then export TEST_ONLY=1; cd oshinko-s2i; make test-pyspark-radio ; fi
- if [ "$TO_TEST" = "java-templates" ]; then export TEST_ONLY=1; cd oshinko-s2i; make test-java-radio ; fi
- if [ "$TO_TEST" = "scala-templates" ]; then export TEST_ONLY=1; cd oshinko-s2i; make test-scala-radio ; fi
notifications:
 email:
   on_success: never
   on_failure: never
